apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
spec:
  containers:
    - name: nginx
      image: localhost/custom-nginx:latest
      ports:
        - containerPort: 80
          hostPort: 80

    - name: fastapi-app
      image: localhost/fastapi-app:latest
      ports:
        - containerPort: 8000
          hostPort: 8000
  volumes:
    - name: nginx-conf
      hostPath:
        path: /home/ubuntu/ppflooring-website/nginx/nginx.conf

